export {BanClicker} from "./BanClicker"
export {Payment} from "./Payment"
export {Rules} from "./Rules"
export {ClickerBtn} from "./ClickerBtn"
export {handleClick, handleClose} from "./snippets"
export {Result} from "./Result"
